// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#ifndef PRACTICA_1_H
#define PRACTICA_1_H

#include <ngrest/common/Service.h>
#include <string>
#include "Lista.h"
#include "PilaRecurso.h"
#include "ColaServicio.h"
#include <list>

//! Dummy description for the service
/*! Some detailed description of the service */
// '*location' comment sets resource path for this service
// *location: practica_1
class Practica_1: public ngrest::Service
{
public:	
		// *method: POST
    	// *location: /newUser
    	std::string newUser(const usuario& user);

    	// *method: POST
    	// *location /newRecurso
		std::string newRecurso(const recurso& rec);	

		// *method: GET
		// *location /getUsuarios
    	std::list<usuario> getUsuarios();

    	// *method: GET
    	// *location /getColaServicios
   		std::list<servicio> getColaServicio();	


   		// *method: GET
   		// *location /getRecurso/{id_usuario}
   		servicio getRecurso(const std::string& idUsuario);	


      std::string prueba();

};


#endif // PRACTICA_1_H



